AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersTable
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: UsersTable
  PollsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PollsTable
      AttributeDefinitions:
      - AttributeName: poll_id
        AttributeType: S
      - AttributeName: created_by
        AttributeType: S
      KeySchema:
      - AttributeName: poll_id
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: CreatedByIndex
        KeySchema:
        - AttributeName: created_by
          KeyType: HASH
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: PollsTable
  ResponsesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ResponsesTable
      AttributeDefinitions:
      - AttributeName: response_id
        AttributeType: S
      - AttributeName: poll_id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      KeySchema:
      - AttributeName: response_id
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: PollUserIndex
        KeySchema:
        - AttributeName: poll_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: ResponsesTable
Outputs:
  UsersTableArn:
    Description: ARN of the DynamoDB Users Table
    Value:
      Fn::GetAtt:
      - UsersTable
      - Arn
    Export:
      Name: UsersTableArn
  PollsTableArn:
    Description: ARN of the DynamoDB Polls Table
    Value:
      Fn::GetAtt:
      - PollsTable
      - Arn
    Export:
      Name: PollsTableArn
  ResponsesTableArn:
    Description: ARN of the DynamoDB Responses Table
    Value:
      Fn::GetAtt:
      - ResponsesTable
      - Arn
    Export:
      Name: ResponsesTableArn
